unique_ids:
  assets:
    standard-page.html: D2VP5XYV27M7REYY3J5AP4EGYY3JTF7K
    theme.css: JCQYIVBSAG2UWWWL7ZK56SNWN7VDRSXN
  forms:
    Form1: SM27CAT7HHJ7QCTMYRTXZJP3ADAQTO5I
  modules: {}
  scripts: {}
  server_modules: {}
